apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-project
  template:
    metadata:
      labels:
        app: email-project
    spec:
      containers:
      - name: application
        image: registry.digitalocean.com/email-project/main:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: do-registry
