---
apiVersion: v1
kind: Service
metadata:
  name: email-project-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: email-project
